export const GET_CAREER_RUNS = 'GET_CAREER_RUNS';
export const GET_CAREER_HIGH_SCORES = 'GET_CAREER_HIGH_SCORES';
export const GET_CAREER_HUNDREDS = 'GET_CAREER_HUNDREDS';
export const GET_CAREER_AVERAGE = 'GET_CAREER_AVERAGE';
export const UPDATE_CAREER_BATTING_CHART = 'UPDATE_CAREER_BATTING_CHART';
