export const GET_ALL_PLAYERS = 'GET_ALL_PLAYERS';
export const GET_PLAYERS_BY_APPEARANCES = 'GET_PLAYERS_BY_APPEARANCES';
export const GET_PLAYER_PROFILE = 'GET_PLAYER_PROFILE';
export const GET_PLAYER_APPEARANCES = 'GET_PLAYER_APPEARANCES';